# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Backend / NodeJS / PHP Developer & Architect Tomáš Strejček - CV
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.ghn.cz:4000" # the base hostname & protocol for your site
twitter_username: TomasStrejcek
github_username:  tomasstrejcek

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-19269803-1

collections:
  - cs_apps
  - cs_profile
  - cs_hackathons
  - cs_info
  - cs_jobs
  - cs_publishing
  - cs_references
  - cs_schools
  - cs_skills
  - cs_skills_intro
  - cs_talks
